// <AUTO-GENERATE>
// This File Is Auto Generated By UIComponentEditor
// </AUTO-GENERATE>

using UnityEngine.UI;
using UnityEngine;
using UIFlow.UIComponent;

public partial class UIBag
{
    private RectTransform Bg;
    private RectTransform Item;
    private Button Close;

    public override bool BindComponent()
    {
        if (prefabInstance == null) 
        {
            Debug.LogError("UIBag，绑定组件失败，没有实例资源");
            return false;
        }
        var uiComponent = prefabInstance.GetComponent<UIComponent>();
        if (uiComponent == null)
        {
            Debug.LogError("UIBag，绑定组件失败，没有实例资源");
            return false;
        }
        Bg =  uiComponent.GetComponent<RectTransform>(0);
        Item =  uiComponent.GetComponent<RectTransform>(1);
        Close =  uiComponent.GetComponent<Button>(2);
        return true;
    }
}
