// <AUTO-GENERATE>
// This File Is Auto Generated By UIComponentEditor
// </AUTO-GENERATE>

using UnityEngine.UI;
using UnityEngine;
using UIFlow.UIComponent;

public partial class UIBag
{
    private RectTransform Bg;
    private RectTransform Item;
    private Button Close;

    public override bool BindComponent(GameObject instance)
    {
        if (instance == null) 
        {
            Debug.LogError("UIBag，绑定组件失败，没有实例资源");
            return false;
        }
        var uiComponent = instance.GetComponent<UIComponent>();
        if (uiComponent == null)
        {
            Debug.LogError("UIBag，绑定组件失败，缺少UIComponent");
            return false;
        }
        Bg =  uiComponent.GetComponent<RectTransform>(0);
        if (Bg == null) return false;
        Item =  uiComponent.GetComponent<RectTransform>(1);
        if (Item == null) return false;
        Close =  uiComponent.GetComponent<Button>(2);
        if (Close == null) return false;
        prefabInstance = instance;
        return true;
    }
}
