// <AUTO-GENERATE>
// This File Is Auto Generated By UIComponentEditor
// </AUTO-GENERATE>

using UIFlow.UIComponent;
using UnityEngine;
using UnityEngine.UI;

public partial class UILogin
{
    private Transform test1;
    private Image test2;
    
    
    private bool BindComponent(GameObject prefab)
    {
        var uiComponent = prefab.GetComponent<UIComponent>();
        if (uiComponent == null) 
            return false;
        test1 = uiComponent.GetComponent<Transform>(0);
        return true;
    }
}
