// <AUTO-GENERATE>
// This File Is Auto Generated By UIComponentEditor
// </AUTO-GENERATE>

using UnityEngine.UI;
using UnityEngine;
using UIFlow.UIComponent;

public partial class UIWorld
{
    private Text Name;
    private Button Bag;

    public override bool BindComponent()
    {
        if (prefabInstance == null) 
        {
            Debug.LogError("UIWorld，绑定组件失败，没有实例资源");
            return false;
        }
        var uiComponent = prefabInstance.GetComponent<UIComponent>();
        if (uiComponent == null)
        {
            Debug.LogError("UIWorld，绑定组件失败，没有实例资源");
            return false;
        }
        Name =  uiComponent.GetComponent<Text>(0);
        Bag =  uiComponent.GetComponent<Button>(1);
        return true;
    }
}
