// <AUTO-GENERATE>
// This File Is Auto Generated By UIComponentEditor
// </AUTO-GENERATE>

using UnityEngine.UI;
using UnityEngine;
using UIFlow.UIComponent;

public partial class UIWorld
{
    private Text Name;
    private Button Bag;
    private RectTransform Money;
    private Image Icon;

    public override bool BindComponent()
    {
        if (prefabInstance == null) 
        {
            Debug.LogError("UIWorld，绑定组件失败，没有实例资源");
            return false;
        }
        var uiComponent = prefabInstance.GetComponent<UIComponent>();
        if (uiComponent == null)
        {
            Debug.LogError("UIWorld，绑定组件失败，没有实例资源");
            return false;
        }
        Name =  uiComponent.GetComponent<Text>(0);
        if (Name == null) return false;
        Bag =  uiComponent.GetComponent<Button>(1);
        if (Bag == null) return false;
        Money =  uiComponent.GetComponent<RectTransform>(2);
        if (Money == null) return false;
        Icon =  uiComponent.GetComponent<Image>(3);
        if (Icon == null) return false;
        return true;
    }
}
